services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: chat_db
    ports:
      - "5432:5432"
    volumes:
      - my_db_data:/var/lib/postgresql/data

volumes:
  my_db_data:
